name: 🚀  Deploy WebHook Fn

on:
  workflow_dispatch:

env:
  rg: cdfunc
  ghes: https://colindembovsky-0cd7b2095901bb090.gh-quality.net
  org: central
  repo: ephemeral-runner

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      runs:
        working-directory: MonaResponder

    steps:
    - uses: actions/checkout@2
    - name: az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create function app
      run: |
        ./deploy-function.yml
      working-directory: infra
      env:
        rg: ${{ env.rg }}
        server: ${{ env.ghes }}
        pat: ${{ secrets.REPO_PAT }}
        org: ${{ env.org }}
        repo: ${{ env.repo }}
    - name: Install func tools
      run: |
        npm install -g azure-functions-core-tools
    - name: Build
      run: |
        npm run build:production
    - name: Pack function
      run: |
        func pack
    - name: Deploy function
      run: |
        az functionapp deploy -n ${{ env.rg }}fn -g ${{ env.rg }} --src-path MonaResponder.zip