name: 🚀  Deploy WebHook Fn

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  rg: cdfunc
  ghes: https://colindembovsky-0cd7b2095901bb090.gh-quality.net
  org: central
  repo: ephemeral-runner

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MonaResponder

    steps:
    - uses: actions/checkout@v2
    - name: az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create function app
      run: ../infra/deploy.sh
      env:
        rg: ${{ env.rg }}
        server: ${{ env.ghes }}
        pat: ${{ secrets.REPO_PAT }}
        org: ${{ env.org }}
        repo: ${{ env.repo }}
    - name: Install func tools
      run: npm install -g azure-functions-core-tools
    - name: Install packages
      run: npm install
    - name: Build
      run: npm run build:production
    - name: Pack function
      run: func pack
    - name: Deploy function
      run: az functionapp deploy -n ${{ env.rg }}fn -g ${{ env.rg }} --src-path MonaResponder.zip
    - name: Display URL
      run: |
        url=$(az functionapp show -g ${{ env.rg }} -n ${{ env.rg }}fn --query "hostNames[0]" -o tsv)
        key=$(az functionapp keys list -g ${{ env.rg }} -n ${{ env.rg }}fn --query "functionKeys.default" -o tsv)
        
        echo "URL for WebHook is https://$url/api/WorkflowJob?code=$key"